<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>pfp.ico</ApplicationIcon>
      <!-- Single EXE -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Don't include debug symbols -->
    <DebugType>none</DebugType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\minecraft_font.ttf" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="pfp.ico" />
  </ItemGroup>

<ItemGroup>
    <EmbeddedResource Update="Fonts\minecraft_font.ttf">
        <LogicalName>HPSkyStatusClient.Fonts.minecraft_font.ttf</LogicalName>
    </EmbeddedResource>
</ItemGroup>
<ItemGroup>
    <EmbeddedResource Include="skyblock-green.ico" />
    <EmbeddedResource Include="skyblock-yellow.ico" />
    <EmbeddedResource Include="skyblock-red.ico" />

    <EmbeddedResource Include="skyblock-green-notify.ico" />
    <EmbeddedResource Include="skyblock-yellow-notify.ico" />
    <EmbeddedResource Include="skyblock-red-notify.ico" />

    <EmbeddedResource Include="Fonts\minecraft_font.ttf" />
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


</Project>